# Generated by Django 3.2.13 on 2022-05-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=29966019, max_length=8),
            preserve_default=False,
        ),
    ]
