# Generated by Django 3.2.13 on 2022-05-19 01:44

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20220519_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=userprofile.models.nameFile),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=userprofile.models.nameFile),
        ),
    ]
